# Generated by Django 5.0.1 on 2024-01-22 10:12

import admin_employee.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_master', '0005_subjects_classsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegistrationTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')])),
                ('DateOfBirth', models.DateField()),
                ('Mobile', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=100)),
                ('JoiningDate', models.DateField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to=admin_employee.models.dynamic_upload_to)),
                ('QRcode', models.ImageField(blank=True, null=True, upload_to='QR_images/')),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'deactive')], default=1)),
                ('EmployeeCatagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.employeecatagorydb')),
                ('EmployeeDepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.departmentdb')),
                ('EmployeeDesignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.designationdb')),
                ('EmployeeQualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.qualificationdb')),
            ],
        ),
        migrations.CreateModel(
            name='EmpDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FromDate', models.DateField()),
                ('ToDate', models.DateField(blank=True, null=True)),
                ('Designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.departmentdb')),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employeeregistrationtb')),
            ],
        ),
        migrations.CreateModel(
            name='EmpDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FromDate', models.DateField()),
                ('ToDate', models.DateField(blank=True, null=True)),
                ('Department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.departmentdb')),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employeeregistrationtb')),
            ],
        ),
        migrations.CreateModel(
            name='EmpSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Salary', models.DecimalField(decimal_places=2, max_digits=100)),
                ('FromDate', models.DateField()),
                ('ToDate', models.DateField(blank=True, null=True)),
                ('Employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employeeregistrationtb')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectClassDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.divisiondb')),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employeeregistrationtb')),
                ('Subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.subjects')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.class_newdb')),
            ],
        ),
    ]
