# Generated by Django 5.0.1 on 2024-01-23 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_employee', '0001_initial'),
        ('admin_master', '0005_subjects_classsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdesignation',
            name='Designation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.designationdb'),
        ),
    ]
