# Generated by Django 5.0.1 on 2024-01-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=255)),
                ('departmentCode', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'deactive')], default=1)),
            ],
        ),
    ]
