# Generated by Django 5.0.1 on 2024-01-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0003_classdb_designationdb_divisiondb_qualificationdb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_NEWdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'deactive')], default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Classdb',
        ),
    ]
