# Generated by Django 5.0.1 on 2024-01-17 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0004_class_newdb_delete_classdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'active'), (0, 'deactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.class_newdb')),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.subjects')),
            ],
        ),
    ]
